language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install .
  - pip install -r requirements/requirements-testing.txt
before_script:
  - psql -U postgres -c "create user django_schemas with password 'django_schemas'"
  - psql -U postgres -c "create database django_schemas"
  - psql -U postgres -c "grant all on database django_schemas to django_schemas"
  - psql -U postgres -c "create database django_schemas_2"
  - psql -U postgres -c "grant all on database django_schemas_2 to django_schemas"
  - psql -U postgres -c "grant all on database postgres to django_schemas"
  - psql -U postgres -c "create extension postgis" django_schemas_2
script:
  - tox
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
addons:
  postgresql: "9.3"