language: python
python:
  - "3.4"
install:
  - pip install .
  - pip install -r requirements.txt
before_script:
  - psql -U postgres -c "create database travis_ci_test;"
  - psql -U postgres -c "create extension postgis"
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres